# Generated by Django 5.2.6 on 2026-09-09 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('delete', 'Delete'), ('reprocess', 'Reprocess')], max_length=32)),
                ('outcome', models.CharField(default='success', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_user_created_idx')],
            },
        ),
    ]
