# Generated by Django 5.2.6 on 2026-09-09 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField()),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='chunk_doc_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_doc_chunk_index')],
            },
        ),
    ]
