# Generated by Django 5.2.6 on 2026-09-09 18:07

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('manage', 'Manage')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_document_permissions', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='rbac.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='doc_owner_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document', 'permission'], name='doc_perm_doc_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['user', 'permission'], name='doc_perm_user_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['role', 'permission'], name='doc_perm_role_perm_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__isnull', True), ('user__isnull', False)), models.Q(('role__isnull', False), ('user__isnull', True)), _connector='OR'), name='doc_perm_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('document', 'user', 'permission'), name='uniq_doc_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('document', 'role', 'permission'), name='uniq_doc_role_permission'),
        ),
    ]
